dbt_recon:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('DBT_HOST', 'spark-thrift-server') }}"
      port: 10000
      schema: nessie.db
      threads: 4
